We want to support a JavaBean as input and output types.

The input is a  `Book` object:

[source,java]
.src/main/java/example/micronaut/Book.java
----
include::{sourceDir}/src/main/java/example/micronaut/Book.java[]
----

<1> Annotate the class with `@Introspected` to generate the Bean Metainformation at compile time.
<2> `name` is required
<3> Add a nullability annotation to help with Kotlin interoperability and help the IDE.

The output is a `BookSaved` object:

[source,java]
.src/main/java/example/micronaut/BookSaved.java
----
include::{sourceDir}/src/main/java/example/micronaut/BookSaved.java[]
----

<1> Annotate the class with `@Introspected` to generate the Bean Metainformation at compile time.
<2> `name` and `isbn` are required
<3> Add a nullability annotation to help with Kotlin interoperability and help the IDE.


The application contains a class extending https://micronaut-projects.github.io/micronaut-aws/latest/api/io/micronaut/function/aws/MicronautRequestHandler.html[MicronautRequestHandler]

[source,java]
.src/main/java/example/micronaut/BookRequestHandler.java
----
include::{sourceDir}/src/main/java/example/micronaut/BookRequestHandler.java[]
----

<1> The class extends https://micronaut-projects.github.io/micronaut-aws/latest/api/io/micronaut/function/aws/MicronautRequestHandler.html[MicronautRequestHandler] and defines input and output types.

The generated test shows how the verify the function behaviour:

[source,java]
.src/test/java/example/micronaut/BookRequestHandlerTest.java
----
include::{sourceDir}/src/test/java/example/micronaut/BookRequestHandlerTest.java[]
----

<1> When you instantiate the Handler, the application context starts.
<2> Remember to close your application context when you end your test. You can use your handler to obtain it.
<3> Invoke the `execute` method of the handler.